require 'axlsx'
require 'securerandom'
require 'colorize'
require 'nokogiri'
require 'open-uri'
require 'pry'

require_relative './scrape_indeed/version'
require_relative './scrape_indeed/cli'
require_relative './scrape_indeed/graphic'
require_relative './scrape_indeed/scrape'
require_relative './scrape_indeed/excel'
